# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intentra < Formula
  desc "Observability for AI Coding Assistants"
  homepage "https://intentra.sh"
  version "0.17.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intentrahq/intentra-cli/releases/download/v0.17.0/intentra_0.17.0_darwin_amd64.tar.gz"
      sha256 "472b25c97a6f70f32abd9bdef8094692ab057f4a926d77a6e7c35080f7ca6b80"

      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intentrahq/intentra-cli/releases/download/v0.17.0/intentra_0.17.0_darwin_arm64.tar.gz"
      sha256 "655c0c761b1cd5dcc3a22ada6cb72fbc38fd6bbe52374dcad7a6974514581d90"

      define_method(:install) do
        bin.install "intentra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intentrahq/intentra-cli/releases/download/v0.17.0/intentra_0.17.0_linux_amd64.tar.gz"
      sha256 "c7db8b93ae78900633652378654db17556d3a1ad7a564f6403b54b62a4835a86"
      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intentrahq/intentra-cli/releases/download/v0.17.0/intentra_0.17.0_linux_arm64.tar.gz"
      sha256 "f9fa07b2aae64e597ec47751992ceffa9a81413ba4627bdeff0b487e8f1bd78b"
      define_method(:install) do
        bin.install "intentra"
      end
    end
  end

  test do
    system "#{bin}/intentra", "--version"
  end
end
