# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intentra < Formula
  desc "Observability for AI Coding Assistants"
  homepage "https://intentra.sh"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.14.0/intentra_0.14.0_darwin_amd64.tar.gz"
      sha256 "c5afed044170e60aa9e77e06824c1ec2e06b2f9278c08d524101166abc308dd2"

      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.14.0/intentra_0.14.0_darwin_arm64.tar.gz"
      sha256 "98bbe623aa6c4d3402cd70a36ba9c31d0ec4553d4f0b3a3004006aab55c99844"

      define_method(:install) do
        bin.install "intentra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.14.0/intentra_0.14.0_linux_amd64.tar.gz"
      sha256 "f6cca4220d706651ecf3550ad8085033b11113d29750c7788b6cb3ee92c2d017"
      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.14.0/intentra_0.14.0_linux_arm64.tar.gz"
      sha256 "3fc0b1c4e71fcf00630fcf4311f96ee0fe2e09cb358b2acb65da665a1991278c"
      define_method(:install) do
        bin.install "intentra"
      end
    end
  end

  test do
    system "#{bin}/intentra", "--version"
  end
end
